# Generated by Django 3.1.5 on 2021-03-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='I must have been too lazy to make a summary...'),
        ),
    ]
