# Generated by Django 3.1.5 on 2021-03-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/images/logo.jpg', upload_to='article_images'),
        ),
    ]
