# Generated by Django 3.1.5 on 2021-03-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/images/logo.jpg', upload_to='article_images'),
        ),
    ]
