# Generated by Django 3.1.5 on 2021-03-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210314_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='static/images/logo.jpg', upload_to='article_images'),
        ),
    ]
