# Generated by Django 3.1.5 on 2021-03-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
