# Generated by Django 3.1.5 on 2021-03-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/images/logo.jpg', upload_to='article_images'),
        ),
    ]
