# Generated by Django 3.1.5 on 2021-03-15 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/static/images/logo.jpeg', upload_to='article_images'),
        ),
    ]
