# Generated by Django 3.1.5 on 2021-03-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(default='I must have been too lazy to make a summary...'),
        ),
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(blank=True, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
