# Generated by Django 3.1.5 on 2021-03-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210330_1452'),
        ('blog', '0002_post_summary'),
    ]

    operations = [
    ]
